[package]
name = "axum-health"
version = "0.1.2"
edition = "2021"
authors = ["Alan Baumgartner"]
license = "MIT OR Apache-2.0"
keywords = ["axum", "diesel", "sqlx", "sea-orm"]
readme = "README.md"
repository = "https://github.com/alanbaumgartner/axum-health"
homepage = "https://github.com/alanbaumgartner/axum-health"
documentation = "https://docs.rs/axum-health"
description = """
Spring Boot like health indicators.
"""
exclude = ["/tests", "/.github"]

[dependencies]
tokio = { version = "1" }
async-trait = { version = "0" }
axum = { version = "0.8" }
serde = { version = "1", features = ["derive"] }
tower-layer = { version = "0.3" }
futures = { version = "0.3" }

diesel = { version = "2", default-features = false, optional = true }
diesel-async = { version = "0.6", default-features = false, optional = true }
sea-orm = { version = "1", default-features = false, optional = true }
sqlx = { version = "0.8", default-features = false, optional = true }
scylla = { version = "1", default-features = false, optional = true }
elasticsearch = { version = "9.1.0-alpha.1", default-features = false, optional = true }
mongodb = { version = "3", default-features = false, optional = true }
neo4rs = { version = "0.9.0-rc.8", default-features = false, optional = true }
redis = { version = "1.0.0-alpha.1", default-features = false, optional = true }

sysinfo = { version = "0.37", optional = true, default-features = false, features = ["disk"] }

[features]
default = []

diesel-deadpool = ["database", "diesel-async", "diesel-async/deadpool"]
diesel-mobc = ["database", "diesel-async", "diesel-async/mobc"]
diesel-bb8 = ["database", "diesel-async", "diesel-async/bb8"]
diesel-async = ["database", "diesel", "dep:diesel-async"]

diesel-r2d2 = ["database", "diesel", "diesel/r2d2"]
diesel = ["database", "dep:diesel", "diesel/i-implement-a-third-party-backend-and-opt-into-breaking-changes"]

sea-orm = ["database", "dep:sea-orm"]
sqlx = ["database", "dep:sqlx"]

cassandra = ["database", "dep:scylla"]
elasticsearch = ["database", "dep:elasticsearch"]
mongo = ["database", "dep:mongodb"]
neo4j = ["database", "dep:neo4rs"]
neo4j-summary = ["neo4j", "neo4rs/unstable-bolt-protocol-impl-v2"]
redis = ["database", "dep:redis"]

database = []

disk = ["dep:sysinfo"]

[dev-dependencies]
diesel-async = { version = "0.6", features = ["mysql", "sqlite", "postgres", "deadpool", "mobc", "bb8"] }
diesel = { version = "2", features = ["r2d2", "mysql", "sqlite", "postgres"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "mysql", "sqlite", "postgres"] }
sea-orm = { version = "1", features = ["sqlx-postgres", "sqlx-mysql", "sqlx-sqlite"] }
axum-test = "18"
tokio = { version = "1", features = ["test-util"] }
testcontainers = { version = "0.25.0" }
testcontainers-modules = { version = "0.13", features = ["postgres", "mysql"] }
mongodb = { version = "3" }

[[example]]
name = "simple"

[[example]]
name = "diesel"
required-features = ["database", "diesel", "diesel/sqlite"]

[[example]]
name = "sea_orm"
required-features = ["database", "sea-orm", "sea-orm/sqlx-sqlite"]

[[example]]
name = "sqlx"
required-features = ["database", "sqlx", "sqlx/sqlite"]

[[example]]
name = "neo4j"
required-features = ["database", "neo4j"]

[[example]]
name = "cassandra"
required-features = ["database", "cassandra"]

[[example]]
name = "redis"
required-features = ["database", "redis"]

[[example]]
name = "mongo"
required-features = ["database", "mongo"]

[[example]]
name = "elasticsearch"
required-features = ["database", "elasticsearch"]

