name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --features=sqlx-postgres,diesel-postgres,sea-orm-postgres,sqlx-mysql,diesel-mysql,sea-orm-mysql,sqlx-sqlite,diesel-sqlite,sea-orm-sqlite
